### ISSUE TITLE
Phantom process isn't shutting down correctly after test run

### ISSUE THREAD

**Issue by trabianmatt** [trabian/trabian-webapp-core#11]
After running `grunt test:watch` (and perhaps at other times), occasionally the `phantom` process isn't shutting down completely. Not only does this prevent those resources from being reclaimed, but it also causes duplication of subsequent test runs.

For me this seems to happen more often on the larger projects such as [trabian/vantage-banking](https://github.com/trabian/vantage-banking).

@shipstar - does this match the behavior you were seeing as well?

**Comment by shipstar** [comment]
Yep. Thought it was reliably reproducible, but I had processes hanging around from yesterday. I'll keep an eye out for a reproduction.
